### ISSUE TITLE
Cannot get the package to work

### ISSUE THREAD

**Issue by kevinagius** [StartAutomating/obs-powershell#140]
I have just upgraded to PowerShell 7 to run this package however when I run the following _Install-Module obs-powershell -Scope CurrentUser -Force_ to install it I am getting this error. 

**WARNING: The version '2.0.3' of module 'ThreadJob' is currently in use. Retry the operation after closing the applications.**

I have closed everything, restarted my PC and this above error is still showing up.

_Running Import-Module obs-powershell -PassThru -Force_ seems to be functioning properly 

However _Connect-OBS -WebSocketToken $myToken_ yields a **"Cannot index into a null array"** error

I run _Get-OBSHotKey_ command it show me a **MethodInvocationException: C:\Users\kevin\Documents\Powershell\Modules\obs-powershell\0.1.9\Commands\Send-OBS.ps1:151** with further details of **Exception calling "SendAsync" with "4" argument(s): "Cannot access a disposed object. Object name: 'System.Net.WebSockets.ClientWebSocket'."**

Can someone please help me with installing this package as it would help me immensely and I have been stuck on this for days now and I have searched multiple forums but I can't find anything

**Comment by kevinagius** [comment]
If you could also help me with making a Powershell script which sends the Hotkey for Key number 2 I would truly appreciate it.

**Comment by StartAutomating** [comment]
@kevinagius this sounds like ThreadJob's problem.

I wonder if you have an old copy of ThreadJob.

Alternatively, I can think of a couple of other possibilities:

1. You could be running an older copy of obs (perhaps with the websocket disabled)
2.  The password to the websocket might be wrong (which would auto close the web socket, thus giving you that "disposed" object error).

There's also a slightly known annoyance of getting an indexing error upon the very first connection (an issue needs to be filed for it, and, if you're falling into that rabbit hole, this would be it).

It's especially annoying because it just displays the error and then works just fine after the first command (of the very first connection).

So, let's try a few things:

1. Update-Module ThreadJob -Force (just in case)
2. Share your $psVersionTable (just in case)
3. Connect-OBS with a token directly copied / pasted from the field.  If you used a different port, you may need to also provide a URI to localhost.
4. Double check to see if commands work, despite the error.
5. If they do, import the module again and confirm there is no error.

**Comment by StartAutomating** [comment]
Can you assign Connect-OBS to a variable, and then pipe it to `Receive-Job -Keep`?

Get-OBSHotKey is working for me.

My best guess is something wrong during connection.

**Comment by kevinagius** [comment]
Doesn't seem to be working :/ 

![image](https://github.com/StartAutomating/obs-powershell/assets/38814307/a8a4d202-3e53-4c6f-8414-28a3d2cafce6)


For reference here are my settings:
![image](https://github.com/StartAutomating/obs-powershell/assets/38814307/c3eee7cd-e6ff-4bdf-9dbd-6bb797ac7421)

**Comment by kevinagius** [comment]
Just got a connection: 
![image](https://github.com/StartAutomating/obs-powershell/assets/38814307/97b4b121-7fe9-4602-9e97-010d5d9ca954)

And I can see it successfully on OBS:
![image](https://github.com/StartAutomating/obs-powershell/assets/38814307/eb782415-3545-48ac-bf8f-59c6089e20c1)

I will be trying to send hotkeys now. I will keep you updated

**Comment by kevinagius** [comment]
Unbelievable! I managed to get to work! 
![image](https://github.com/StartAutomating/obs-powershell/assets/38814307/58f1ea26-276a-440b-9e3a-1d186e829e03)

Recording started and stopped as required. You have no idea how happy I am. I am very grateful for your help and support, and I truly appreciate your work. You have made my life a million times easier.

Issue closed!!
